[package]
name = "range-set"
version = "0.0.7"
authors = ["Shane Pearman <spearman@github.com>", "Alex Moon <alex.r.moon@gmail.com>"]
license = "Apache-2.0"
description = "Smallvec-backed containers of sorted integer ranges"
repository = "https://github.com/spearman/range-set"
readme = "README.md"

[dependencies]
num-traits = "0.2.*"
serde = { version = "1.0.*", optional = true }
smallvec = { version = "0.6.*" }

[features]
serde = ["dep:serde", "smallvec/serde"]